# Generated by Django 6.0.4 on 2026-05-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='employee_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
